@echo off
del /q dist\*
echo Build with pyinstaller...
pyinstaller ticker.py --onefile -n iidxseg
echo Create an archive...
powershell Compress-Archive -Path dist\*.exe -DestinationPath dist\iidxseg_release.zip